// Bundles dbskill SKILL.md + knowledge packs into skills-data.js for the browser.
// Run with:  node build.mjs

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join } from 'path';

const ROOT = 'H:/IPskills/dbskill';
const SKILLS_DIR = join(ROOT, 'skills');
const KNOWLEDGE_DIR = join(ROOT, '知识库/Skill知识包');
const DICTIONARY_FILE = join(ROOT, '知识库/高频概念词典.md');
const OUT = 'H:/IPskills/dbskill-frontend/skills-data.js';

const KNOWLEDGE_MAP = {
  'dbs-diagnosis':   ['diagnosis_公理与诊断框架.md', 'diagnosis_问题消解案例库.md'],
  'dbs-benchmark':   ['benchmark_对标方法论.md', 'benchmark_平台运营知识.md'],
  'dbs-content':     ['content_内容创作方法论.md', 'content_平台特性与案例.md'],
  'dbs-action':      ['action_心理诊断框架.md', 'action_信号案例库.md'],
  'dbs-deconstruct': ['deconstruct_语言与概念框架.md', 'deconstruct_解构案例库.md'],
};

// Display metadata — UI grouping, icon, friendly Chinese label.
// hidden: true → 不在 sidebar 显示,但 skill 本身仍然加载,可由其他路径触发(如 dbs-report 通过 📊 按钮)
const SKILL_META = {
  'dbs':                   { group: '主入口',   icon: '⚡', label: '主入口(自动路由)' },
  'dbs-content':           { group: '内容',     icon: '✍️', label: '内容创作诊断' },
  'dbs-xhs-title':         { group: '内容',     icon: '📝', label: '小红书标题公式' },
  'dbs-hook':              { group: '内容',     icon: '🎬', label: '短视频开头优化' },
  'dbs-ai-check':          { group: '内容',     icon: '🤖', label: 'AI 味检测' },
  'dbs-benchmark':         { group: '策略',     icon: '🎯', label: '对标分析' },
  'dbs-diagnosis':         { group: '策略',     icon: '🔍', label: '商业模式诊断' },
  'dbs-goal':              { group: '策略',     icon: '🎯', label: '目标清晰化' },
  'dbs-deconstruct':       { group: '策略',     icon: '🧩', label: '概念拆解' },
  'dbs-action':            { group: '执行',     icon: '🚀', label: '执行力诊断' },
  'dbs-slowisfast':        { group: '执行',     icon: '🐢', label: '慢就是快' },
  'dbs-chatroom':          { group: '辅助',     icon: '💬', label: '多视角讨论室' },
  'dbs-chatroom-austrian': { group: '辅助',     icon: '🏛️', label: '奥派经济讨论室' },

  // 隐藏:已被顶部 💾📂📊 按钮替代,放 sidebar 多余
  'dbs-save':              { group: '状态',     icon: '💾', label: '存档',         hidden: true },
  'dbs-restore':           { group: '状态',     icon: '📂', label: '恢复',         hidden: true },
  'dbs-report':            { group: '状态',     icon: '📊', label: '生成报告',     hidden: true },
  // 隐藏:跟小红书内容诊断无关的 Agent 工程师工具
  'dbs-agent-migration':   { group: '基建',     icon: '🛠️', label: 'Agent 工作台迁移', hidden: true },
};

function parseFrontmatter(content) {
  const match = content.match(/^---\s*\r?\n([\s\S]*?)\r?\n---\s*\r?\n([\s\S]*)$/);
  if (!match) return { meta: {}, body: content };
  const yaml = match[1];
  const body = match[2];
  const meta = {};
  const lines = yaml.split(/\r?\n/);
  let currentKey = null;
  let buf = [];
  let inMultiline = false;
  for (const line of lines) {
    if (inMultiline) {
      if (/^\s+/.test(line) || line === '') {
        buf.push(line.replace(/^\s{2}/, ''));
        continue;
      } else {
        meta[currentKey] = buf.join('\n').trim();
        inMultiline = false;
      }
    }
    const m = line.match(/^(\w[\w-]*):\s*(.*)$/);
    if (m) {
      currentKey = m[1];
      if (m[2] === '|' || m[2] === '>') {
        inMultiline = true;
        buf = [];
      } else {
        meta[currentKey] = m[2].replace(/^["']|["']$/g, '');
      }
    }
  }
  if (inMultiline && currentKey) meta[currentKey] = buf.join('\n').trim();
  return { meta, body };
}

const dirs = readdirSync(SKILLS_DIR).filter(d => statSync(join(SKILLS_DIR, d)).isDirectory());
const skills = {};
let totalBytes = 0;

for (const name of dirs) {
  const skillPath = join(SKILLS_DIR, name, 'SKILL.md');
  let raw;
  try { raw = readFileSync(skillPath, 'utf-8'); }
  catch { console.warn('SKIP no SKILL.md:', name); continue; }
  const { meta, body } = parseFrontmatter(raw);
  const knowledgeFiles = KNOWLEDGE_MAP[name] || [];
  const knowledge = knowledgeFiles.map(f => ({
    name: f,
    content: readFileSync(join(KNOWLEDGE_DIR, f), 'utf-8'),
  }));
  const display = SKILL_META[name] || { group: '其他', icon: '•', label: name };
  skills[name] = {
    name,
    label: display.label,
    icon: display.icon,
    group: display.group,
    hidden: !!display.hidden,
    description: meta.description || '',
    body,
    knowledge,
  };
  totalBytes += body.length + knowledge.reduce((s, k) => s + k.content.length, 0);
}

let dictionary = '';
try { dictionary = readFileSync(DICTIONARY_FILE, 'utf-8'); }
catch { console.warn('SKIP 高频概念词典.md not found'); }

const payload = `// Auto-generated by build.mjs — do not edit by hand.
window.DBS_SKILLS = ${JSON.stringify(skills)};
window.DBS_GROUPS = ${JSON.stringify(['主入口', '内容', '策略', '执行', '辅助'])};
window.DBS_DICTIONARY = ${JSON.stringify(dictionary)};
`;

writeFileSync(OUT, payload, 'utf-8');
console.log(`Wrote ${OUT}`);
console.log(`Skills: ${Object.keys(skills).length}`);
console.log(`Total content: ${(totalBytes / 1024).toFixed(1)} KB`);
console.log(`File size:     ${(payload.length / 1024).toFixed(1)} KB`);
